import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {createVerifier} from '../src/auth.mjs';
import {createHandler} from '../src/http.mjs';
import {validatePanel} from '../src/domain.mjs';
const panel={key:'site-admin',nameFa:'مدیر سایت',nameEn:'Site Admin',group:'employees',ownerService:'site-content',requiredScopes:['content-read']};
const principal={subject:'operator-1',tenantId:'airline-a',roles:['platform-admin'],scopes:['panel.read','panel.write']};
function handler(){const calls=[];return {calls,handle:createHandler({authenticate:async h=>h==='Bearer valid'?principal:null,store:{list:async tenant=>{calls.push(tenant);return []},register:async value=>({panel:value.panel,replayed:false})}})}}
test('site admin is constrained to employees',()=>{assert.equal(validatePanel(panel).group,'employees');assert.throws(()=>validatePanel({...panel,group:'management'}),{code:'SITE_ADMIN_GROUP'})});
test('anonymous and wrong role cannot read or write',async()=>{const {handle}=handler();assert.equal((await handle(new Request('https://core.test/v1/platform/panels'))).status,401);const low=createHandler({authenticate:async()=>({...principal,roles:['employee'],scopes:['panel.read']}),store:{list:async()=>[],register:async()=>{throw Error('should not run')}}});assert.equal((await low(new Request('https://core.test/v1/platform/panels',{method:'POST',headers:{'idempotency-key':'abcdefghijklmnop'},body:JSON.stringify(panel)}))).status,403)});
test('tenant-scoped list and validated registration',async()=>{const {handle,calls}=handler();const listed=await handle(new Request('https://core.test/v1/platform/panels',{headers:{authorization:'Bearer valid'}}));assert.equal(listed.status,200);assert.deepEqual(calls,['airline-a']);const created=await handle(new Request('https://core.test/v1/platform/panels',{method:'POST',headers:{authorization:'Bearer valid','idempotency-key':'abcdefghijklmnop'},body:JSON.stringify(panel)}));assert.equal(created.status,201);assert.equal((await created.json()).panel.group,'employees')});
test('OIDC signature, issuer, audience, expiry and tenant are checked',async()=>{const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});const jwk=publicKey.export({format:'jwk'});const verify=createVerifier({issuer:'https://issuer.test',audience:'core',jwksUrl:'https://issuer.test/jwks',fetcher:async()=>new Response(JSON.stringify({keys:[{...jwk,kid:'a',use:'sig'}]}))});const header=Buffer.from(JSON.stringify({alg:'RS256',kid:'a'})).toString('base64url');const payload=Buffer.from(JSON.stringify({iss:'https://issuer.test',aud:'core',sub:'u1',tenant_id:'t1',exp:Math.floor(Date.now()/1000)+60,scope:'panel.read'})).toString('base64url');const signed=header+'.'+payload;const token=signed+'.'+sign('RSA-SHA256',Buffer.from(signed),privateKey).toString('base64url');assert.equal((await verify('Bearer '+token)).tenantId,'t1');assert.equal(await verify('Bearer '+token+'x'),null)});
